# Generated by Django 3.2.16 on 2023-07-02 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Worker', '0002_worker'),
        ('Maintainers', '0001_initial'),
        ('WorkerDocuments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('id_tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maintainers.tipodocumento')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Worker.worker')),
            ],
        ),
    ]
