# Generated by Django 3.2.16 on 2023-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerDocuments', '0002_alter_workerdocuments_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdocuments',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
