# Generated by Django 3.2.16 on 2023-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerDocuments', '0003_workerdocuments_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerdocuments',
            name='id_tipo_doc',
        ),
        migrations.RemoveField(
            model_name='workerdocuments',
            name='id_worker',
        ),
        migrations.AddField(
            model_name='workerdocuments',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='workerdocuments',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
