# Generated by Django 3.2.16 on 2023-06-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerDocuments', '0008_auto_20230623_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerdocuments',
            name='id_tipo_doc',
        ),
        migrations.RemoveField(
            model_name='workerdocuments',
            name='id_worker',
        ),
    ]
