# Generated by Django 3.2.16 on 2023-06-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='id_estado',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
