# Generated by Django 3.2.16 on 2023-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tipodiscapacidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodiscapacidad',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Descripcion'),
        ),
    ]
