# Generated by Django 3.2.16 on 2023-06-14 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=50)),
                ('rut_company', models.CharField(max_length=9)),
                ('adress', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('estado_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estado.estado')),
            ],
        ),
    ]
