# Generated by Django 3.2.16 on 2023-07-02 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_company'),
        ('Workplace', '0002_workplace'),
        ('Maintainers', '0002_comuna_discapacidad_estado_region_sexo_tipodiscapacidad_tipodocumento'),
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=9, verbose_name='RUT')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fec_nac', models.DateField(null=True, verbose_name='Fecha de Nacimiento (Formato año/mes/dia)')),
                ('fec_ing', models.DateField(null=True, verbose_name='Fecha de Ingreso (Formato año/mes/dia)')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Maintainers.comuna', verbose_name='Comuna')),
                ('estado_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maintainers.estado', verbose_name='Estado')),
                ('id_Discapacidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Maintainers.discapacidad', verbose_name='Tiene Alguna Discapacidad')),
                ('id_Tipo_discapacidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Maintainers.tipodiscapacidad', verbose_name='Indique la que corresponda')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company', verbose_name='Empresa')),
                ('id_workplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Workplace.workplace', verbose_name='Centro')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Maintainers.region', verbose_name='Región')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maintainers.sexo', verbose_name='Género')),
            ],
        ),
    ]
