# Generated by Django 3.2.16 on 2023-07-02 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Worker', '0002_worker'),
        ('Workplace', '0002_workplace'),
        ('Maintainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='id_workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Workplace.workplace', verbose_name='Centro'),
        ),
        migrations.AddField(
            model_name='worker',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Maintainers.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='worker',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maintainers.sexo', verbose_name='Género'),
        ),
    ]
