# Generated by Django 3.2.16 on 2023-06-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0003_alter_estado_id_estado'),
        ('Workplace', '0001_initial'),
        ('Generoworker', '0001_initial'),
        ('Worker', '0002_auto_20230616_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='estado_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Estado.estado'),
        ),
        migrations.AddField(
            model_name='worker',
            name='id_Genworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Generoworker.generoworker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='id_workplace',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='Workplace.workplace'),
        ),
    ]
