# Generated by Django 3.2.16 on 2023-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0003_auto_20230620_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='discapacidad',
            field=models.BinaryField(default=True, verbose_name='Es_Discapacitado'),
        ),
    ]
