# Generated by Django 3.2.16 on 2023-06-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workplace', '0001_initial'),
        ('Worker', '0004_worker_discapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='discapacidad',
            field=models.BinaryField(null=True, verbose_name='Es_Discapacitado'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Workplace.workplace'),
        ),
    ]
