# Generated by Django 3.2.16 on 2023-06-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0003_alter_estado_id_estado'),
        ('Worker', '0008_worker_id_discapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='estado_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estado.estado'),
        ),
    ]
