# Generated by Django 3.2.16 on 2023-06-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0003_alter_estado_id_estado'),
        ('Generoworker', '0001_initial'),
        ('Tipodiscapacidad', '0002_alter_tipodiscapacidad_name'),
        ('Company', '0001_initial'),
        ('Workplace', '0001_initial'),
        ('Discapacidad', '0001_initial'),
        ('Worker', '0009_alter_worker_estado_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='id_tipo_discapacidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Tipodiscapacidad.tipodiscapacidad', verbose_name='Indique la que corresponda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='estado_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estado.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_Discapacidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Discapacidad.discapacidad', verbose_name='Tiene Alguna DIscapacidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_Genworker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Generoworker.generoworker', verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_workplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Workplace.workplace', verbose_name='Centro'),
            preserve_default=False,
        ),
    ]
