# Generated by Django 3.2.16 on 2023-06-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discapacidad', '0001_initial'),
        ('Worker', '0010_auto_20230620_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fec_ing',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='worker',
            name='fec_nac',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_Discapacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Discapacidad.discapacidad', verbose_name='Tiene Alguna Discapacidad'),
        ),
    ]
