# Generated by Django 3.2.16 on 2023-06-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estado', '0003_alter_estado_id_estado'),
        ('Company', '0001_initial'),
        ('Discapacidad', '0001_initial'),
        ('Generoworker', '0001_initial'),
        ('Workplace', '0001_initial'),
        ('Worker', '0010_auto_20230620_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='estado_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estado.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_Discapacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Discapacidad.discapacidad', verbose_name='Tiene Alguna DIscapacidad'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_Genworker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Generoworker.generoworker', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Workplace.workplace', verbose_name='Centro'),
        ),
    ]
