# Generated by Django 3.2.16 on 2023-06-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0011_auto_20230620_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fec_nac',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
