# Generated by Django 3.2.16 on 2023-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0012_alter_worker_fec_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fec_ing',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
