# Generated by Django 3.2.16 on 2023-06-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0013_alter_worker_fec_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fec_ing',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso (Formato año/mes-dia)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fec_nac',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento (Formato año/mes-dia)'),
        ),
    ]
