# Generated by Django 3.2.16 on 2023-06-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0014_auto_20230620_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fec_ing',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso (Formato año/mes/dia)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fec_nac',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento (Formato año/mes/dia)'),
        ),
    ]
