# Generated by Django 3.2.16 on 2023-06-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0015_auto_20230621_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id_Discapacidad',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='id_tipo_discapacidad',
        ),
    ]
