# Generated by Django 3.2.16 on 2023-06-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Estado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id_workplace', models.AutoField(primary_key=True, serialize=False)),
                ('name_workplace', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('estado_workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estado.estado')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company')),
            ],
        ),
    ]
