# Generated by Django 3.2.16 on 2023-07-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_Comuna', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Comunas')),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_Discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2, verbose_name='Discapacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_Region', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodiscapacidad',
            fields=[
                ('id_Tipo_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Tipo discapacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id_Tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Archivo')),
            ],
        ),
    ]
