# Generated by Django 3.2.16 on 2023-07-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Archivo'),
        ),
    ]
