# Generated by Django 3.2.16 on 2023-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generoworker',
            fields=[
                ('id_Genworker', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Descripcion')),
            ],
        ),
    ]
